import { db } from "./client";
import { cardTypes, cards } from "@siege/shared/db-schema";

await db.delete(cards);
await db.delete(cardTypes);

await db.insert(cardTypes).values([
  { id: 1, type: "Leader" },
  { id: 2, type: "Castle" },
  { id: 3, type: "Food" },
  { id: 4, type: "Morale" },
  { id: 5, type: "Siege Engine" },
  { id: 6, type: "Siege Defense" },
  { id: 7, type: "Espionage" },
]);

await db.insert(cards).values([
  // ── Leaders (Monarch) ───────────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 1,
    typeIcon: "img/aethelred.png",
    name: "Aethelred the Unready",
    deckPoints: null,
    cost: null,
    action: "+1 to defense on Invader's second attack in a turn",
    effect: "-1 to attack at range 2",
    flavorText: "He swore he was prepared. He lied.",
  },
  {
    isMonarch: true,
    typeId: 1,
    typeIcon: "img/richard.png",
    name: "Richard the Lesser",
    deckPoints: null,
    cost: null,
    action: "+1 to attack at range 2",
    effect: "+1 food consumed when building siege defenses",
    flavorText: "Less like a crusade, and more like study abroad",
  },

  // ── Leaders (Invader) ───────────────────────────────────────────────
  {
    isMonarch: false,
    typeId: 1,
    typeIcon: "img/charlemaybe.png",
    name: "Charlemaybe",
    deckPoints: null,
    cost: null,
    action: "+1 to morale when troops attack",
    effect: "-1 defense to supply line",
    flavorText: "Definitely not the greatest Charles, but not the worst either",
  },
  {
    isMonarch: false,
    typeId: 1,
    typeIcon: "img/madking.png",
    name: "The Mad King",
    deckPoints: null,
    cost: null,
    action: "+1 to siegecraft",
    effect: "-1 to morale",
    flavorText: "That boy crazy",
  },

  // ── Castles (Monarch) ───────────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 2,
    typeIcon: null,
    name: "Camelot",
    deckPoints: null,
    cost: null,
    action: "+2 to wall defense",
    effect: "Morale cards cost 1 less food",
    flavorText: "It is a silly place.",
  },
  {
    isMonarch: true,
    typeId: 2,
    typeIcon: null,
    name: "Ironhold",
    deckPoints: null,
    cost: null,
    action: "+1 to all ranged defenses",
    effect: "-1 to troop movement speed",
    flavorText: "Built to last. Lasted.",
  },

  // ── Food (both) ─────────────────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 3,
    typeIcon: null,
    name: "Royal Grain Stores",
    deckPoints: 4,
    cost: 2,
    action: "Feed 3 troops this turn",
    effect: "Cannot be used during a siege",
    flavorText: "Taxed from peasants who were already hungry.",
  },
  {
    isMonarch: true,
    typeId: 3,
    typeIcon: null,
    name: "Salted Pork",
    deckPoints: 6,
    cost: 3,
    action: "Feed 5 troops this turn",
    effect: "+1 morale for each troop fed",
    flavorText: "It keeps. Mostly.",
  },
  {
    isMonarch: false,
    typeId: 3,
    typeIcon: null,
    name: "Pillaged Stores",
    deckPoints: 5,
    cost: 2,
    action: "Feed 4 troops, remove 1 food from Monarch",
    effect: "Cannot be played on first turn",
    flavorText: "Sharing is caring. Caring is weakness.",
  },
  {
    isMonarch: false,
    typeId: 3,
    typeIcon: null,
    name: "Field Rations",
    deckPoints: 3,
    cost: 1,
    action: "Feed 2 troops this turn",
    effect: "None",
    flavorText: "Barely edible. Extremely portable.",
  },

  // ── Morale (both) ───────────────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 4,
    typeIcon: null,
    name: "Royal Decree",
    deckPoints: 8,
    cost: 3,
    action: "+2 morale to all defending troops",
    effect: "Costs 1 extra food to play",
    flavorText: "By order of the crown. And also by order of the sword.",
  },
  {
    isMonarch: true,
    typeId: 4,
    typeIcon: null,
    name: "Rallying Cry",
    deckPoints: 6,
    cost: 2,
    action: "+1 morale to all troops in range 1",
    effect: "None",
    flavorText: "Loud enough to hear over the screaming.",
  },
  {
    isMonarch: false,
    typeId: 4,
    typeIcon: null,
    name: "War Drums",
    deckPoints: 8,
    cost: 3,
    action: "+2 morale to attacking troops",
    effect: "-1 morale if attack fails",
    flavorText: "The beat that keeps the siege moving.",
  },
  {
    isMonarch: false,
    typeId: 4,
    typeIcon: null,
    name: "Battle Standard",
    deckPoints: 6,
    cost: 2,
    action: "+1 morale to all troops in range 2",
    effect: "Destroyed if bearer is defeated",
    flavorText: "A flag. A very important flag.",
  },

  // ── Siege Engine (Invader) ──────────────────────────────────────────
  {
    isMonarch: false,
    typeId: 5,
    typeIcon: null,
    name: "Trebuchet",
    deckPoints: 15,
    cost: 6,
    action: "+4 to attack at range 3",
    effect: "Cannot move and fire in the same turn",
    flavorText: "Technically a traction trebuchet. Don't correct him.",
  },
  {
    isMonarch: false,
    typeId: 5,
    typeIcon: null,
    name: "Battering Ram",
    deckPoints: 10,
    cost: 4,
    action: "+3 to gate attack",
    effect: "-2 to all other attacks",
    flavorText: "One trick. Great trick.",
  },
  {
    isMonarch: false,
    typeId: 5,
    typeIcon: null,
    name: "Siege Tower",
    deckPoints: 12,
    cost: 5,
    action: "Troops may attack from elevation",
    effect: "Flammable",
    flavorText: "A moving building. What could go wrong.",
  },

  // ── Siege Defense (Monarch) ─────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 6,
    typeIcon: null,
    name: "Raised Drawbridge",
    deckPoints: 10,
    cost: 4,
    action: "+3 to gate defense",
    effect: "Troops cannot exit while active",
    flavorText: "Very good at keeping things out. Also in.",
  },
  {
    isMonarch: true,
    typeId: 6,
    typeIcon: null,
    name: "Boiling Oil",
    deckPoints: 8,
    cost: 3,
    action: "+2 to wall defense, -1 morale to attackers",
    effect: "Single use",
    flavorText: "Hot. Very hot. Too hot.",
  },
  {
    isMonarch: true,
    typeId: 6,
    typeIcon: null,
    name: "Arrow Slits",
    deckPoints: 6,
    cost: 2,
    action: "+1 to ranged defense on all walls",
    effect: "None",
    flavorText: "Small holes. Big problems for the other guy.",
  },

  // ── Espionage (both) ────────────────────────────────────────────────
  {
    isMonarch: true,
    typeId: 7,
    typeIcon: null,
    name: "Counter-Spy",
    deckPoints: 10,
    cost: 4,
    action: "Negate one Invader Espionage card",
    effect: "Must be played in response",
    flavorText: "He works for us. We think.",
  },
  {
    isMonarch: false,
    typeId: 7,
    typeIcon: null,
    name: "Double Agent",
    deckPoints: 12,
    cost: 5,
    action: "View Monarch's hand, discard one card",
    effect: "Revealed if Counter-Spy is played",
    flavorText: "He works for them. Probably.",
  },
  {
    isMonarch: false,
    typeId: 7,
    typeIcon: null,
    name: "Saboteur",
    deckPoints: 8,
    cost: 3,
    action: "-1 to one Monarch Siege Defense for 2 turns",
    effect: "Captured if attack on that wall fails",
    flavorText: "He just works here.",
  },
]);

console.log("Seed complete");
